### ISSUE TITLE
As a user I want to delete a timetable entry

### ISSUE THREAD

**Issue by emer7** [CS2103JAN2018-W15-B1/main#26]

**Comment by IzHoBX** [comment]
As of current design, duplicated timetable entries are allowed (which makes sense because some events happen repeatedly, e.g. monthly report submission). 
Since we use google calendar to display the timetable entry, there's no index like the PersonsCards for users to specify which timetable entry. So it will be difficult to implement timetable entry deletion. 
Thus, postponed this issue until design difficulties are overcome.
